# Generated by Django 5.1.6 on 2025-02-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Sample Collector', 'Sample Collector'), ('Sales Person', 'Sales Person'), ('Lab Technician', 'Lab Technician'), ('Doctor', 'Doctor'), ('Accounts', 'Accounts')], max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
