# Generated by Django 4.1.13 on 2025-03-03 11:01

import backend_diagnostics.models
import bson.objectid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_groups',
            fields=[
                ('email', models.EmailField(max_length=500, unique=True)),
                ('employee_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('id', backend_diagnostics.models.ObjectIdField(default=bson.objectid.ObjectId, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=50, unique=True)),
                ('employeeName', models.CharField(max_length=100)),
                ('fatherName', models.CharField(blank=True, max_length=100, null=True)),
                ('motherName', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('maritalStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('guardianNumber', models.CharField(blank=True, max_length=150, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhaarNumber', models.CharField(max_length=12, unique=True)),
                ('panNumber', models.CharField(max_length=10, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('bankDetails', models.JSONField(default=dict)),
                ('qualifications', models.JSONField(default=list)),
                ('experiences', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
